# Generated by Django 3.0.5 on 2020-04-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_auto_20200225_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Lawyer', 'Lawyer'), ('Witness', 'Witness'), ('Plaintiff', 'Plaintiff'), ('Judge', 'Judge')], max_length=255),
        ),
    ]
