# Generated by Django 3.0.5 on 2020-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20200426_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='verdict',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
