# Generated by Django 3.0.5 on 2020-04-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20200426_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('postphoned', 'PostPhoned'), ('closed', 'Closed')], default='pending', max_length=100),
        ),
    ]
