# Generated by Django 3.0.5 on 2020-04-27 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0006_auto_20200427_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='witness/%Y/%m/%d/')),
                ('phone_number', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wit_case', to='case.Case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witness_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
