# Generated by Django 3.0.5 on 2020-04-27 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_auto_20200427_1046'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_case', to='case.Case'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
